### ISSUE TITLE
SyntaxError: Invalid or unexpected token

### ISSUE THREAD

**Issue by zohar** [endroid/qr-code#276]
Newbie here...

I ran `composer require endroid/qr-code` and then used the code from the [Advanced Usage](https://github.com/endroid/qr-code#advanced-usage).

I then receive 
```
/path/to/qrcode.js:1
use Endroid\QrCode\ErrorCorrectionLevel;
    ^^^^^^^^

SyntaxError: Invalid or unexpected token
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by endroid** [comment]
Hi @zohar sorry but this is a PHP library not a JS library.

**Comment by zohar** [comment]
doh... :-)
